variables:
  DOCKER_REGISTRY: 514404768813.dkr.ecr.us-east-2.amazonaws.com
  AWS_DEFAULT_REGION: us-east-2
  APP_NAME: launches-private
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

image: openjdk:11-stretch
services:
  - docker:dind

stages:
  - build
  - test
  - deploy

build:
  image: openjdk:11-stretch
  stage: build
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  stage: test
  artifacts:
    paths: [gl-code-quality-report.json]

test:
  stage: test
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew check

deploy_staging:
  stage: deploy
  image:
    name: docker:latest
  services:
    - docker:19-dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - aws --version
    - docker info
    - docker --version
  script:
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:latest .
    - docker push $DOCKER_REGISTRY/$APP_NAME:latest
  only:
    - main
    - develop